require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Use min_ios_version_supported from React Native configuration
platform :ios, '14.0'
prepare_react_native_project!

# Flipper versions
$RNFirebaseAsStaticFramework = true
$FlipperConfiguration = FlipperConfiguration.disabled  # Temporarily disable Flipper

target 'RoamExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :flipper_configuration => $FlipperConfiguration
  )

  pod 'RNRoam', :path => '../node_modules/roam-reactnative'

  target 'RoamExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)

    # Ensure deployment target is set correctly for each target
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        
        # Force the use of C++17
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        
        # Exclude arm64 architecture for iPhone simulators
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end

    # Workaround for Xcode 14 warnings
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        end
      end
    end
  end
end